Resources:
  UsersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.table.user}

      GlobalSecondaryIndexes:
        - IndexName: ${self:custom.index.email}
          KeySchema:
            - AttributeName: email
              KeyType: HASH

          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  
  # Table to control access to api
  AppsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:

      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.table.app}