frameworkVersion: ">=1.78.1"
service: practice-user

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  tags:
    project: practice-user   
    #this is used to separate variables for local use that are not needed in prod
  # memorize
  environment: 
    CONFIG: ${file(config.${self:custom.currentStage}.json):config}
resources:
  - ${file(src/resources/tables.yml)}

functions:
  #lambas associated with user
  - ${file(src/user/user.yml)}
  #lambdas associated with authorization
  - ${file(src/authorizer/authorizer.yml)}

custom:
  table: 
    user: users
    app: apps
  
  # manage stage 
  currentStage: ${opt:stage, self:provider.stage}