frameworkVersion: ">=1.78.1"
service: practice-user

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  tags:
    project: practice-user
    
    #this is used to separate variables for local use that are not needed in prod
  environment: ${file(environment/${self:custom.currentStage}.serverless.yml)}

resources:
  - ${file(src/resources/tables.serverless.yml)}

functions:
  #lambas associated with user
  - ${file(src/handler/user.serverless.yml)}

custom:
  table: 
    user: users
  
  # manage stage 
  currentStage: ${opt:stage, self:provider.stage}